### ISSUE TITLE
NMS restarting on Juju update status

### ISSUE THREAD

**Issue by markbeierl** [canonical/sdcore-nms-k8s-operator#90]
#### Describe the bug

Every time the update status event is fired, the Pebble service is restarted.

#### To Reproduce

1. Deploy NMS with sdcore
2. Watch the nms charm logs
3. Notice the following every 5 minutes:

```
2024-03-19T14:42:05.458Z [pebble] GET /v1/plan?format=yaml 937.18µs 200
2024-03-19T14:42:05.487Z [pebble] POST /v1/layers 1.154532ms 200
2024-03-19T14:42:05.501Z [pebble] POST /v1/services 12.730647ms 202
2024-03-19T14:42:05.540Z [pebble] Service "sdcore-nms" stopped
2024-03-19T14:42:05.550Z [pebble] Service "sdcore-nms" starting: /bin/bash -c 'cd /app && npm run start'
```

#### Expected behavior

NMS refresh status should not cause the service to restart.

#### Additional context

I suspect it is this that is causing the issue: https://github.com/canonical/sdcore-nms-k8s-operator/blob/main/src/charm.py#L94

With log forwarding, the pebble plan is not what we expect it to be. This is the actual plan, and so the NMS thinks it needs to replan pebble, which causes the log forwarder to detect the change and put back the log forwarding layer.

```
log-targets:
  grafana-agent/0:
    labels:
      charm: sdcore-nms-k8s
      juju_application: nms
      juju_model: control-plane
      juju_model_uuid: a94efd67-d781-4941-8449-32f598b7f6e2
      juju_unit: nms/0
      product: Juju
    location: http://grafana-agent-0.grafana-agent-endpoints.control-plane.svc.cluster.local:3500/loki/api/v1/push
    override: replace
    services:
    - all
    type: loki
services:
  nms:
    command: npm run start
    environment:
      GNB_CONFIG_PATH: /etc/gnb/gnb.json
      UPF_CONFIG_PATH: /etc/upf/upf.json
      WEBUI_ENDPOINT: http://10.1.182.9:5000
    override: replace
    startup: enabled
    working-dir: app
  sdcore-nms:
    command: /bin/bash -c 'cd /app && npm run start'
    environment:
      GNB_CONFIG_PATH: /nms/config/gnb_config.json
      UPF_CONFIG_PATH: /nms/config/upf_config.json
      WEBUI_ENDPOINT: http://10.1.235.152:5000
    override: replace
    startup: enabled
```
